In [2]:
import numpy as np

MELHORIA 1:

1. Se o elemento abaixo do pivô for zero, continue.
2. Se um dos pivôs for zero, mostrar uma mensagem de erro.

In [78]:
# Dado um sistema S, representado por uma matriz M de ordem N e por uma matriz resultado R de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a M e sua matriz resultado correspondente

# Aplicando a melhoria 1

def escalonamento(a,b,n):
    for k in range(n-1):
        for i in range(k+1,n):
            if a[i,k] == 0: continue
            if a[i,k] == 0: print("A iteração ", k, " não deveria ser executada")
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            for j in range(k+1,n):
                a[i,j] = a[i,j] - m*a[k,j]
            b[i,0] = b[i,0] - m*b[k,0]

In [80]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3 ==> 2*x1 será substituído por 0*x1
# 3*x1 - 1*x2 - 2*x3 = -4

O = np.matrix([[1,2,1],[0,1,-1],[3,-1,-2]])
P = np.matrix([[9],[3],[-4]])

escalonamento(O,P,3)
print("\n", O)
print("\n", P)


 [[  1   2   1]
 [  0   1  -1]
 [  0   0 -12]]

 [[  9]
 [  3]
 [-10]]


In [88]:
# Dado um sistema S, representado por uma matriz M de ordem N e por uma matriz resultado R de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a M e sua matriz resultado correspondente

# Aplicando a melhoria 2

def escalonamento2(a,b,n):
    for k in range(n-1):
        if a[k,k] == 0:
            print("Pivô 0")
            break
        for i in range(k+1,n):
            if a[i,k] == 0: continue
            if a[i,k] == 0: print("A iteração ", k, " não deveria ser executada")
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            for j in range(k+1,n):
                a[i,j] = a[i,j] - m*a[k,j]
            b[i,0] = b[i,0] - m*b[k,0]

In [90]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9 ==> 1*x1 será substituído por 0*x1
# 2*x1 + 1*x2 - 1*x3 =  3
# 3*x1 - 1*x2 - 2*x3 = -4

O = np.matrix([[0,2,1],[2,1,-1],[3,-1,-2]])
P = np.matrix([[9],[3],[-4]])

escalonamento2(O,P,3)
print("\n", O)
print("\n", P)

Pivô 0

 [[ 0  2  1]
 [ 2  1 -1]
 [ 3 -1 -2]]

 [[ 9]
 [ 3]
 [-4]]


In [91]:
Amat  = np.matrix([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])
Aarr  = np.array([[3, 2, 4, -1], [0, 1, 0, 3], [0, -3, -5, 7], [0, 2, 4, 0] ])


A = Amat
print(A)

k = 1
i = 2
n = np.shape(A)[0] - 1#último index
print('n ', n, '\n')

#slicing
print( np.array( A[ i : n + 1, k ] ) )

#Localizando o  maior valor na coluna do pivô, depois do pivô
col = A[ i : n + 1, k ]

colAbs = np.abs( col )
print( 'colAbs \n', colAbs )

indexMax = np.argmax( colAbs )
print( indexMax )


#Trocando a coluna
iChange = indexMax + i
print( iChange )

aux = np.copy( A[ k, : ] )
print( aux )

A[ k, : ] = np.copy( A[ iChange, : ] )
A[ iChange, : ] = np.copy( aux )

print(A)

[[ 3  2  4 -1]
 [ 0  1  0  3]
 [ 0 -3 -5  7]
 [ 0  2  4  0]]
n  3 

[[-3]
 [ 2]]
colAbs 
 [[3]
 [2]]
0
2
[[0 1 0 3]]
[[ 3  2  4 -1]
 [ 0 -3 -5  7]
 [ 0  1  0  3]
 [ 0  2  4  0]]
